# Generated by Django 5.2.10 on 2026-03-10 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'carrier',
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('countries', models.JSONField(blank=True, null=True)),
                ('provinces', models.JSONField(blank=True, null=True)),
                ('cities', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shipping_zone',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=50, unique=True)),
                ('order_id', models.IntegerField()),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('shipping_address_id', models.IntegerField(blank=True, null=True)),
                ('ship_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='ship.carrier')),
            ],
            options={
                'db_table': 'shipment',
                'ordering': ['-ship_date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estimated_days', models.IntegerField(blank=True, null=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='ship.carrier')),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='ship.shippingzone')),
            ],
            options={
                'db_table': 'shipping_rate',
            },
        ),
    ]
